# Assignment 1

## Name
Zahra Ghahremani
#Student ID 114141861

### Collaborators: 
Yavar Pourmohamad


# Notes

Submit your homework by uploading it in the directory with your name. Please mention in this file the names of any students with whom you collaborated. If you didn't collaborate with anyone, mark your collaborators as "None." 
Remember, your goal is to communicate. Full credit will be given only to correct solutions which are described clearly. Convoluted and obtuse descriptions will receive low marks. 
To complete your homework, you may ONLY consult the following material: 
1.	lecture slides
2.	course notes you or others took during lecture.
3.	the required text (CLRS)
4.	websites that may clarify the concepts covered in the material but do not in any way provide complete solutions to the problems.

Deadline

Please provide an answer to the following questions: 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#Question 1 
Create a script that:

1. loads the iris dataset.

At first, I used pandas library and pd.read_csv to read the data. Then, I added name to culomns and dorped the last column for other processes we do not need that column. Finally print the data and statistical summary.

In [ ]:
import pandas as pd
import numpy as np
dataset = pd.read_csv('/content/drive/MyDrive/Spring 2022-MS-Semester2/ML/Notebooks/Copy of iris.csv')  
dataset.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'species']
print(dataset)
datasetPredictor= dataset.drop(columns = ['species'])
print(datasetPredictor.head())
print(' ')
print(datasetPredictor.describe(include='all'))

      f1   f2   f3   f4           class
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]
     sepal length  sepal width  petal length  petal width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...        

In [ ]:
dataset.species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

Showing data distribution


In [ ]:
#showing data distribution
import seaborn as sns
sns.pairplot(data= dataset, hue= 'species')

#Question 1 

2. scales the independent features.
For this part, I scaled data based on Standard scaler method, then convert them to dataframe and add columns name.

In [ ]:
from sklearn.preprocessing import StandardScaler
SS_Model = StandardScaler()
scaled_dataset = SS_Model.fit(datasetPredictor)
scaled_dataset = SS_Model.transform (datasetPredictor)
df_scaled = pd.DataFrame(scaled_dataset, columns = ['Sepal.Length','Sepal.Width','Petal.Length','Petal.Width'])
print(df_scaled.head())
print(' ')
print(df_scaled.describe(include = 'all'))

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0     -0.900681     1.032057     -1.341272    -1.312977
1     -1.143017    -0.124958     -1.341272    -1.312977
2     -1.385353     0.337848     -1.398138    -1.312977
3     -1.506521     0.106445     -1.284407    -1.312977
4     -1.021849     1.263460     -1.341272    -1.312977
 
       Sepal.Length   Sepal.Width  Petal.Length   Petal.Width
count  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02
mean  -2.775558e-16 -5.140333e-16  1.154632e-16  9.251859e-16
std    1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00
min   -1.870024e+00 -2.438987e+00 -1.568735e+00 -1.444450e+00
25%   -9.006812e-01 -5.877635e-01 -1.227541e+00 -1.181504e+00
50%   -5.250608e-02 -1.249576e-01  3.362659e-01  1.332259e-01
75%    6.745011e-01  5.692513e-01  7.627586e-01  7.905908e-01
max    2.492019e+00  3.114684e+00  1.786341e+00  1.710902e+00


#Question 1 
3. computes the correlation coefficients and co-variance among all pairs of independent features.


In [ ]:
print(df_scaled.corr())
print(' ')
print(df_scaled.cov ())

              Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length      1.000000    -0.109369      0.871754     0.817954
Sepal.Width      -0.109369     1.000000     -0.420516    -0.356544
Petal.Length      0.871754    -0.420516      1.000000     0.962757
Petal.Width       0.817954    -0.356544      0.962757     1.000000
 
              Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length      1.006711    -0.110103      0.877605     0.823443
Sepal.Width      -0.110103     1.006711     -0.423338    -0.358937
Petal.Length      0.877605    -0.423338      1.006711     0.969219
Petal.Width       0.823443    -0.358937      0.969219     1.006711


#Question 1 
4. computes the PCA and shows the principal components (their coefficients) 


In [ ]:
from sklearn.decomposition import PCA
import numpy as np
pca_Model = PCA(n_components= 4)
pca_Result = pca_Model.fit(datasetPredictor)
pca_Result = pca_Model.transform(datasetPredictor)
df_pca= pd.DataFrame(pca_Result, columns = ['PC1','PC2','PC3','PC4'])
print(df_pca.head())
print(' ')
print((pca_Model.components_).T)

        PC1       PC2       PC3       PC4
0 -2.684207  0.326607 -0.021512  0.001006
1 -2.715391 -0.169557 -0.203521  0.099602
2 -2.889820 -0.137346  0.024709  0.019305
3 -2.746437 -0.311124  0.037672 -0.075955
4 -2.728593  0.333925  0.096230 -0.063129
 
[[ 0.36158968  0.65653988 -0.58099728  0.31725455]
 [-0.08226889  0.72971237  0.59641809 -0.32409435]
 [ 0.85657211 -0.1757674   0.07252408 -0.47971899]
 [ 0.35884393 -0.07470647  0.54906091  0.75112056]]


#Question 1 
5. computes the correlation coefficient between each original feature and the new features generated by the PCA

In [ ]:
jointDataset = pd.concat([df_scaled, df_pca], axis = 1)
#jointDataset.head()
print(jointDataset.corr().round(3))
print(' ')
print(df_pca.corr().round(3))

              Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    PC1  \
Sepal.Length         1.000       -0.109         0.872        0.818  0.898   
Sepal.Width         -0.109        1.000        -0.421       -0.357 -0.390   
Petal.Length         0.872       -0.421         1.000        0.963  0.998   
Petal.Width          0.818       -0.357         0.963        1.000  0.966   
PC1                  0.898       -0.390         0.998        0.966  1.000   
PC2                  0.390        0.828        -0.049       -0.048  0.000   
PC3                 -0.197        0.385         0.012        0.202  0.000   
PC4                  0.059       -0.115        -0.042        0.151 -0.000   

                PC2    PC3    PC4  
Sepal.Length  0.390 -0.197  0.059  
Sepal.Width   0.828  0.385 -0.115  
Petal.Length -0.049  0.012 -0.042  
Petal.Width  -0.048  0.202  0.151  
PC1           0.000  0.000 -0.000  
PC2           1.000 -0.000 -0.000  
PC3          -0.000  1.000  0.000  
PC4          -0.00

# Question 2 (5 pts + (5 pts Extra))

1. What you can observe by comparing the results in Question 1 sections 4 and 5?
## Answering question:
We can see that there is a high correlation between Sepal.Width, Sepal.Length and Petal.width and low correlation between Petal.length and other variables.
Correlation coefficient between new features created by PCA is equal to zero but it is not equal to zero between original features. Also, the absolute value of the new features created by PCA decreases as we go from PC1 to PC2, PC3, and PC4.




# Question 2 (5 pts + (5 pts Extra))

2. Can you define any property indicated by these results?
## Answering question:
Yes, we can see that correlation of each PC with itself is equal to 1 and its correlation with other PCs is equal to zero. This means that new features created by PCA are orthogonal to each other (the correlation = 0). However, the original data does not have this property and also, the correlation between original data nad new data is not equal to zero.




# Question 2 (5 pts + (5 pts Extra))

3. If there is any property are you able to formally prove it? (5 extra pts)
## Answering question:
We can do this through singular value decomposition $X = USV$, where V are orincipal axis, S is a diagonal matrix with singular values, and U are principal components scaled to unit norm. Standardized PCs van be calculated by $N-1\sqrt{U}$. PCs themselves (also known as "scores") are given by columns of $US$.Theoretically now that covariance matrix is given by $\frac{1}{N-1}X^TX=V\frac{s^2}{N-1}V^T=V\sqrt{E}$, so principal axes V are eigenvectors of the covariance matrix and $E=\frac{s^2}{N-1}$ are its eigenvalues.
Now the cross-covariance matrix (or loadings matrix: it is given by the eigenvectors of the covariance matrix scaled by the square roots of the respective eigenvalues.) between original variables and standardized PCs $$r=ν_{(ij)}\frac{std(Y_{j})}{std(X_{i})}$$where $ν_{ij}$ is an i-th element of the j-th unit-length eigenvector of the covariance matrix, $var(Y_{j})$ is the corresponding eigenvalue which gives variance of this PC, and $std(X_{i})$ is standard deviation of $X_{i}$.

In [ ]:
# for PC1
print(np.std(jointDataset['PC1'])*pca_Model.components_[0]/np.std(df_scaled['Sepal.Width']))
# for PC2
print(np.std(jointDataset['PC2'])*pca_Model.components_[1]/np.std(df_scaled['Petal.Width']))
# for PC3
print(np.std(jointDataset['PC3'])*pca_Model.components_[2]/np.std(df_scaled['Sepal.Length']))
# for PC4
print(np.std(jointDataset['PC4'])*pca_Model.components_[3]/np.std(df_scaled['Petal.Length']))


[ 0.74074495 -0.16853431  1.75475547  0.73512007]
[ 0.32205849  0.35795245 -0.08622078 -0.03664645]
[-0.16226414  0.16657095  0.02025493  0.15334478]
[ 0.04866021 -0.04970929 -0.07357885  0.11520618]


The results are the same as the results in question 1.5.

# Question 3 (10 pts)

1) Write code in pure python (Numpy and Scipy are allowed, SciKit is Not) to implement a decision tree. In input, you should provide the independent features and the dependent feature (the class) separately.
You can assume that the dependent features and the independent feature are binary. Please implement the Gini index and the entropy gain ratio. You can read the code available online, but you cannot plagiarize it.
## answering the question:
 Creating functions for calculating the gini index, split a dataset, and entropy.



In [ ]:
def splitt(index, value, data):
  left, right = list(), list()
  for row in data:
    if row[index] < value:
      left.append(row)
    else:
      right.append(row)
  return left, right


def Gini(groups, classes):
    n_instances = float(sum([len(group) for group in groups]))
    gini = 0.0
    for group in groups:
        size = float(len(group))
        if size == 0:
            continue
        score = 0.0
        for class_val in classes:
            p = [row[-1] for row in group].count(class_val) / size
            score += p * p
        gini += (1.0 - score) * (size / n_instances)
    return gini

def Entropy(groups, classes):
    n_instances = float(sum([len(group) for group in groups]))
    entropy = 0.0
    for group in groups:
        size = float(len(group))
        if size == 0:
            continue
        score = 0.0
        for class_val in classes:
            p = [row[-1] for row in group].count(class_val) / size
            score += p * np.log(p)
        entropy += (- score) * (size / n_instances)
    return entropy

Creating a function to return the group maximum and consider that as a terminal node value

In [ ]:
def Terminal(group):
    outcomes = [row[-1] for row in group]
    return max(set(outcomes), key=outcomes.count)

Crating a split function to produce child splits for a node or make terminal and another function to choose the best split point for a dataset.



In [ ]:
def split(node, max_depth, min_size, depth, Metric):
    left, right = node['groups']
    del(node['groups'])
    if not left or not right:
        node['left'] = node['right'] = Terminal(left + right)
        return
    if depth >= max_depth:
        node['left'], node['right'] = Terminal(left), Terminal(right)
        return
    if len(left) <= min_size:
        node['left'] = Terminal(left)
    else:
        node['left'] = Find_best_split(left,Metric)
        split(node['left'], max_depth, min_size, depth+1, Metric)
    if len(right) <= min_size:
        node['right'] = Terminal(right)
    else:
        node['right'] = Find_best_split(right,Metric)
        split(node['right'], max_depth, min_size, depth+1, Metric)
        
def Find_best_split(data,Metric):
    class_values = list(set(row[-1] for row in data))

    b_index, b_value, b_score, b_groups = 999, 999, 999, None
    for index in range(len(data[0])-1):
        for row in data:
            groups = splitt(index, row[index], data)            
            Metric_index = Metric(groups, class_values)

            if Metric_index < b_score:
                b_index, b_value, b_score, b_groups = index, row[index], Metric_index, groups
    return {'index':b_index, 'value':b_value, 'groups':b_groups}

Decision tree



In [ ]:
def decision_tree(train, max_depth, min_size,Metric):
  root = Find_best_split(train,Metric)
  split(root, max_depth, min_size, 1, Metric)
  def illustrator(root, depth=0):
    if isinstance(root, dict):

      header = 'rank'
      if root['index']+1 == 1:
        header = 'GRE';
      if root['index']+1 == 2:
        header = 'GPA';

      print('%s[%s < %.3f]' % ((depth*' ', (header), root['value'])))
      illustrator(root['left'], depth+1)
      illustrator(root['right'], depth+1)
    else:
      print('%s[%s]' % ((depth*' ', root)))
  illustrator(root)
  return root

# Question 3 (10 pts)
2) Create a toy example to run and test your code (please show the result).

## Answering:
loading the UCLA dataset of admissions (only the first 30 samples)

In [ ]:
Admission = pd.read_csv("/content/drive/MyDrive/Spring 2022-MS-Semester2/ML/HW1/binary.csv")
# link to the dataset: https://stats.idre.ucla.edu/stat/data/binary.csv
change = Admission.pop('admit')
Admission['admit']=change
Admission = Admission.iloc[0:30]
Admission.head()


gre   gpa  rank  admit
0  380  3.61     3      0
1  660  3.67     3      1
2  800  4.00     1      1
3  640  3.19     4      1
4  520  2.93     4      0

Creating train and test dataset

In [ ]:
train = Admission.sample(frac=0.8)
test_mask = pd.Series(True, index=Admission.index)
test_mask[train.index] = False
test = Admission[test_mask]
test.head()

gre   gpa  rank  admit
2   800  4.00     1      1
11  440  3.22     1      0
12  760  4.00     1      1
16  780  3.87     4      0
24  760  3.35     2      1

Train the tree using Gini ratio

In [ ]:
Train_tree = decision_tree(train.values.tolist(), 3, 5, Gini)

[GRE < 540.000]
 [GPA < 3.740]
  [GRE < 480.000]
   [0.0]
   [0.0]
  [1.0]
 [rank < 2.000]
  [1.0]
  [GPA < 3.750]
   [1.0]
   [0.0]


Creating a function to predict based on our tree

In [ ]:
def predictor(node, row):
    if row[node['index']] < node['value']:
        if isinstance(node['left'], dict):
            return predictor(node['left'], row)
        else:
            return node['left']
    else:
        if isinstance(node['right'], dict):
            return predictor(node['right'], row)
        else:
            return node['right']

Checking our trained tree

In [ ]:
Train_results = pd.DataFrame(columns=['decision', 'admit', 'counter'])
i=0
for row in train.values.tolist():
    prediction = predictor(Train_tree, row)
    Train_results.loc[i]=[prediction,row[3],i]
    i+=1
    print('True_observation=%d, Prediction_tree=%d' % (row[-1], prediction))
#Train_results.head()

True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=0, Prediction_tree=0
True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=0, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=1, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=0, Prediction_tree=0
True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=0, Prediction_tree=0
True_observation=0, Prediction_tree=0
True_observation=0, Prediction_tree=0


 true positive, false positive, true negative and false negative



In [ ]:
trained_table = Train_results.groupby(['decision', 'admit'])['counter'].count()
trained_table.unstack()

admit      0.0   1.0
decision            
0.0       10.0   NaN
1.0        3.0  11.0

In [ ]:
accurecy = (trained_table[0][0]+trained_table[1][1])/sum(trained_table)
print('training accurecy is: ' + str(accurecy))

training accurecy is: 0.875


Test data

In [ ]:
Test_resutls= pd.DataFrame(columns=['decision', 'admit', 'counter'])
i=0
for row in test.values.tolist():
    prediction = predictor(Train_tree, row)
    Test_resutls.loc[i]=[prediction,row[3],1]
    i+=1
    print('True_observation=%d, Prediction_tree=%d' % (row[-1], prediction))

True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=1, Prediction_tree=1
True_observation=1, Prediction_tree=1


 true positive, false positive, true negative and false negative


In [ ]:
trained_table = Test_resutls.groupby(['decision', 'admit'])['counter'].count()
trained_table.unstack()

admit     0.0  1.0
decision          
0.0       2.0  NaN
1.0       NaN  4.0

In [ ]:
try:
  trained_table[0][0]
except:
  #print('Nan found!')
  accurecy = (trained_table[1][1])/sum(trained_table)
   
try:
  trained_table[1][1]
except:
  accurecy = (trained_table[0][0])/sum(trained_table)

try:
  trained_table[0][0]
  try:
    trained_table[1][1]
  except:
    accurecy = 0
except:
  print('00')
  
try:
  accurecy = (trained_table[0][0]+trained_table[1][1])/sum(trained_table)
except:
  print('')

print('Test accurecy is: ' + str(accurecy))

Test accurecy is: 1.0


Train the tree using Entropy ratio

In [ ]:
Train_tree = decision_tree(train.values.tolist(), 3, 5, Entropy)

[GRE < 540.000]
 [GRE < 360.000]
  [0.0]
  [0.0]
 [rank < 4.000]
  [GPA < 3.750]
   [1.0]
   [0.0]
  [0.0]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:35: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:35: RuntimeWarning: invalid value encountered in double_scalars


Checking our trained tree

In [ ]:
Train_results = pd.DataFrame(columns=['decision', 'admit', 'counter'])
i=0
for row in train.values.tolist():
    prediction = predictor(Train_tree, row)
    Train_results.loc[i]=[prediction,row[3],1]
    i+=1
    print('True_observation=%d, Prediction_tree=%d' % (row[-1], prediction))

True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=0, Prediction_tree=0
True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=0, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=1, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=0, Prediction_tree=0
True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=0, Prediction_tree=0
True_observation=0, Prediction_tree=0
True_observation=0, Prediction_tree=0


 true positive, false positive, true negative and false negative


In [ ]:
trained_table = Train_results.groupby(['decision', 'admit'])['counter'].count()
trained_table.unstack()

admit      0.0   1.0
decision            
0.0       10.0   NaN
1.0        3.0  11.0

In [ ]:
accurecy = (trained_table[0][0]+trained_table[1][1])/sum(trained_table)
print('training accurecy is: ' + str(accurecy))

training accurecy is: 1.0


Test Data

In [ ]:
Test_resutls= pd.DataFrame(columns=['decision', 'admit', 'counter'])
i=0
for row in test.values.tolist():
    prediction = predictor(Train_tree, row)
    Test_resutls.loc[i]=[prediction,row[3],1]
    i+=1
    print('True_observation=%d, Prediction_tree=%d' % (row[-1], prediction))

True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=1, Prediction_tree=1
True_observation=0, Prediction_tree=0
True_observation=1, Prediction_tree=1
True_observation=1, Prediction_tree=1


true positive, false positive, true negative and false negative

In [ ]:
trained_table = Test_resutls.groupby(['decision', 'admit'])['counter'].count()
trained_table.unstack()

admit     0.0  1.0
decision          
0.0       2.0  NaN
1.0       NaN  4.0

In [ ]:
try:
  trained_table[0][0]
except:
  #print('Nan found!')
  accurecy = (trained_table[1][1])/sum(trained_table)
   
try:
  trained_table[1][1]
except:
  accurecy = (trained_table[0][0])/sum(trained_table)

try:
  trained_table[0][0]
  try:
    trained_table[1][1]
  except:
    accurecy = 0
except:
  print('00')
  
try:
  accurecy = (trained_table[0][0]+trained_table[1][1])/sum(trained_table)
except:
  print('')

print('Test accurecy is: ' + str(accurecy))

Test accurecy is: 1.0


In [ ]:
import pandas as pd
a = 2
b = 3
c = a+ b
print(c)

5
